name: HenCoders RDP Setup

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Mengunduh File yang Diperlukan
      run: |
        Invoke-WebRequedt https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://storage.curvee.eu.org/start-latest.bat -OutFile start.bat
        Invoke-WebRequest https://storage.curvee.eu.org/HenCoders.png -OutFile HenCoders.png
        Invoke-WebRequest https://storage.curvee.eu.org/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://storage.curvee.eu.org/loop.bat -OutFile loop.bat

    - name: Mengekstrak File Ngrok
      run: Expand-Archive ngrok.zip

    - name: Menghubungkan ke Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Mengaktifkan Akses ke RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        copy HenCoders.png C:\Users\Public\Desktop\HenCoders.png
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat

    - name: Membuka Tunnel Ngrok
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Memulai Konfigurasi RDP
      run: cmd /c start.bat

    - name: Mengirim Status ke Render
      run: |
        $ngrokUrl = (Invoke-WebRequest -Uri "http://127.0.0.1:4040/api/tunnels" -UseBasicParsing | ConvertFrom-Json).tunnels[0].public_url
        $data = @{
            "workflow_name" = "HenCoders.yml"
            "status" = "active"
            "url" = $ngrokUrl
            "message" = "RDP telah berhasil dibuat dan aktif."
        } | ConvertTo-Json -Depth 2
        Invoke-RestMethod -Uri "https://henweb-1r9w.onrender.com/api/check-workflow" -Method Post -Body $data -ContentType "application/json"

    - name: Pengaturan Selesai! Anda Bisa Menutup Tab Ini.
      run: cmd /c loop.bat
