name: HenCoders RDP Setup

on:
  workflow_dispatch:
  schedule:
    # Cron job: Jalankan workflow setiap 1 jam
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Mengunduh File yang Diperlukan
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/HenCodersDeveloper/HenDeveloper/refs/heads/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/HenCodersDeveloper/HenDeveloper/refs/heads/main/HenCoders.png -OutFile HenCoders.png
        Invoke-WebRequest https://raw.githubusercontent.com/HenCodersDeveloper/HenDeveloper/refs/heads/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/HenCodersDeveloper/HenDeveloper/refs/heads/main/loop.bat -OutFile loop.bat

    - name: Mengekstrak File Ngrok
      run: Expand-Archive ngrok.zip

    - name: Menghubungkan ke Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Membuka Tunnel Ngrok
      run: |
        Start-Process PowerShell -ArgumentList '-NoExit -Command ".\ngrok\ngrok.exe tcp 3389"' -Wait

    - name: Mengaktifkan Akses ke RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        copy HenCoders.png C:\Users\Public\Desktop\HenCoders.png
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat

    - name: Memulai Konfigurasi RDP
      run: cmd /c start.bat

    - name: Pengaturan Selesai! Anda Bisa Menutup Tab Ini.
      run: cmd /c loop.bat
